services:
  app:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
      target: production
      args:
        - USER_ID=${USER_ID:-3000}
    ports:
      - "${HTTP_PORT:-80}:8080"
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      XDEBUG_HOST: "${XDEBUG_HOST:-host.docker.internal}"
      XDEBUG_PORT: "${XDEBUG_PORT:-9003}"
