version: "3.5"

services:
  milkbar-nginx:
    build: ./build/nginx/
    container_name: milkbar-nginx
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./build/nginx/conf.d/:/etc/nginx/conf.d/
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/
    depends_on:
      - milkbar-php
    networks:
      milkbar_net:
        ipv4_address: 172.31.0.2

  milkbar-php:
    build: ./build/php
    container_name: milkbar-php
    restart: unless-stopped
    working_dir: /var/www
    user: "${USER_ID}"
    volumes:
      - ./:/var/www
      - ./build/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      milkbar_net:
        ipv4_address: 172.31.0.3

  milkbar-mysql:
    image: mysql:5.7
    container_name: milkbar-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./tmp/db/:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      milkbar_net:
        ipv4_address: 172.31.0.4

networks:
  milkbar_net:
    name: milkbar_net
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/24
