version: "3.5"

services:
  nursing-log-php:
    build: ./build/php
    container_name: nursing-log-php
    restart: unless-stopped
    working_dir: /app
    user: "${USER_ID}"
    volumes:
      - ./:/app
      - ./build/php/php.ini:/usr/local/etc/php/php.ini
