version: "3.5"

services:
  nursing-log-nginx:
    build: ./build/nginx/
    container_name: nursing-log-nginx
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./build/nginx/conf.d/:/etc/nginx/conf.d/
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/
    depends_on:
      - nursing-log-php

  nursing-log-php:
    build: ./build/php
    container_name: nursing-log-php
    restart: unless-stopped
    working_dir: /var/www
    user: "${USER_ID}"
    volumes:
      - ./:/var/www
      - ./build/php/php.ini:/usr/local/etc/php/php.ini
